title: Page

tabs:
  content:
    label: Content
    icon: page
    columns:
      main:
        width: 2/3
        fields:
          text:
            type: blocks
            fieldsets:
              - code
              - heading
              - image
              - line
              - list
              - markdown
              - quote
              - text
              - games
              - tournaments


      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
            template: default
          files:
            type: files
